name: Upload to Cloudflare Images
on:
  push:
    branches:
      - master
    paths:
      - "blockchains/**.png"
      - "dapps/**.png"
      - "blockchains/**.jpg"
      - "dapps/**.jpg"
      - "blockchains/**.webp"
      - "dapps/**.webp"
      - 'blockchains/**.svg'
      - 'dapps/**.svg'
  workflow_dispatch:

jobs:
  upload-cf:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'DimensionDev'

    steps:
      - uses: actions/checkout@v2

      - name: Upload images
        shell: pwsh
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          ID_PREFIX: "Assets/"
        run: |
          $imageList = @()
          $pageIndex = 1
          $retry = 0

          while ($true) {
              $resp = try {
                  Invoke-RestMethod -Uri "https://api.cloudflare.com/client/v4/accounts/$($env:CF_ACCOUNT_ID)/images/v1?page=$($pageIndex)&per_page=100" `
                      -SkipHeaderValidation -Headers @{ "Authorization" = "Bearer " + $env:CF_API_TOKEN; }
              }
              catch {
                  [PSCustomObject]@{
                      success = $false;
                      messages = , $_.Exception.Message;
                  }
              }

              if ($resp.success) {
                  if ($resp.result.images.Length -eq 0) {
                      Write-Host "Success: Fetching completed"
                      break
                  }
                  $imageList = ($resp.result.images | Select-Object -ExpandProperty id | ForEach-Object { $_ -Replace "$env:ID_PREFIX", "" }) + $imageList

                  $pageIndex++
                  $retry = 0
              }
              else {
                  $retry++
                  if ($retry -ge 3) {
                      throw "Error: Fetching failed on Page $pageIndex. $($resp.messages[0])"
                  }
              }
          }

          $localList = Get-ChildItem -Recurse -Path "./blockchains/", "./dapps/" -Include "*.png", "*.jpg", "*.webp" , "*.svg" `
          | Resolve-Path -Relative `
          | ForEach-Object { ($_ -Replace "\\", "/").TrimStart("./") }

          $diffList = Compare-Object -ReferenceObject $localList -DifferenceObject $imageList `
          | Where-Object { $_.SideIndicator -eq "<=" } `
          | Select-Object -ExpandProperty InputObject

          $uploaded = 0

          foreach ($imagePath in $diffList) {
              Invoke-WebRequest -Method "POST" -Uri "https://api.cloudflare.com/client/v4/accounts/$($env:CF_ACCOUNT_ID)/images/v1" `
              -SkipHeaderValidation -Headers @{ "Authorization" = "Bearer " + $env:CF_API_TOKEN; } `
              -Form @{
                  "file" = Get-Item -Path $imagePath;
                  "id" = "$env:ID_PREFIX" + "$imagePath";
              }
              
              $uploaded++
              Start-Sleep -Seconds 0.25
          }

          Write-Host "Success: Uploaded $uploaded"
